---
- name: provision devBox
  hosts: local
  user: vagrant
  sudo: yes
 
  roles:
  - { role: basics, tags: [ 'basics' ]}
  - { role: anaconda, tags: [ 'python' ]}

  post_tasks:
    - name: timestamp the execution of ansible
      shell: date >> now.txt
